---
# Based on: https://github.com/AlexNabokikh/windows-playbook/blob/8be81399018d151e5f4f5ea08034fc4bd0ad30da/tasks/explorer.yml

- name: Ensure Explorer includes the file extension in file names for win_explorer_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword
  loop: "{{ win_explorer_users }}"

- name: Ensure Explorer includes the file extension in file names for ansible_user
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword
  when: win_explorer_also_for_ansible_user | bool


- name: Ensure Ribbon menu is disabled in Windows Explorer for win_explorer_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Ribbon
    name: MinimizedStateTabletModeOff
    data: 1
    type: dword
  loop: "{{ win_explorer_users }}"

- name: Ensure Ribbon menu is disabled in Windows Explorer for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Ribbon
    name: MinimizedStateTabletModeOff
    data: 1
    type: dword
  when: win_explorer_also_for_ansible_user | bool


- name: Ensure new right-click context menu disabled for win_explorer_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: ""
    type: string
  loop: "{{ win_explorer_users }}"

- name: Ensure new right-click context menu disabled for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: ""
    type: string
  when: win_explorer_also_for_ansible_user | bool


- name: Disable 'Edit in Notepad' in the right-click context menu for win_explorer_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked
    name: "{CA6CC9F1-867A-481E-951E-A28C5E4F01EA}"
    data: ""
    type: string
  loop: "{{ win_explorer_users }}"

- name: Disable 'Edit in Notepad' in the right-click context menu for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked
    name: "{CA6CC9F1-867A-481E-951E-A28C5E4F01EA}"
    data: ""
    type: string
  when: win_explorer_also_for_ansible_user | bool


- name: Disable 'Onedrive Personal' in the left pane for win_explorer_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{018D5C66-4533-4307-9B53-224DE2ED1FE6}
    state: absent
  loop: "{{ win_explorer_users }}"

- name: Disable 'Onedrive Personal' in the left pane for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace{018D5C66-4533-4307-9B53-224DE2ED1FE6}
    state: absent
  when: win_explorer_also_for_ansible_user | bool
