---
# Based on: https://github.com/AlexNabokikh/windows-playbook/blob/8be81399018d151e5f4f5ea08034fc4bd0ad30da/tasks/explorer.yml

- name: Ensure Explorer includes the file extension in file names.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Ensure Ribbon menu is disabled in Windows Explorer.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Ribbon
    name: MinimizedStateTabletModeOff
    data: 1
    type: dword

- name: Ensure Right-click Context Menu enabled.
  ansible.windows.win_regedit:
    path: >
      HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: ""
    type: string
